In [37]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('Loja.sqlite')
cursor = conn.cursor()

In [38]:
query_clientes = """
    select
        c.Nome,
        p.PedidoID,
        p.DataPedido,
        p.ValorTotal
    from Clientes c
    left join Pedidos p
        on c.ClienteID = p.ClienteID;
"""

resposta = cursor.execute(query_clientes).fetchall()
resposta
df_clientes = pd.DataFrame(resposta, columns=["Nome","PedidoID", "DataPedido", "ValorTotal"])
df_clientes

           Nome  PedidoID  DataPedido  ValorTotal
0     Ana Silva     101.0  2025-01-10       250.0
1  João Pereira     102.0  2025-01-12       100.0
2  João Pereira     103.0  2025-01-15       150.0
3   Maria Souza       NaN        None         NaN

In [39]:
df_clientes = pd.read_sql_query(query_clientes, conn)
df_clientes

           Nome  PedidoID  DataPedido  ValorTotal
0     Ana Silva     101.0  2025-01-10       250.0
1  João Pereira     102.0  2025-01-12       100.0
2  João Pereira     103.0  2025-01-15       150.0
3   Maria Souza       NaN        None         NaN

In [40]:
query_clientes_tot = """
    select
        c.Nome,
        count(p.PedidoID) as QuantidadePedidos,
        sum(p.ValorTotal) as ValorTotalPedidos
    from Clientes c
    inner join Pedidos p
        on c.ClienteID = p.ClienteID
    group by c.Nome, c.ClienteID
    """
resposta = cursor.execute(query_clientes_tot).fetchall()
resposta
df_clientes_tot = pd.DataFrame(resposta, columns=["Nome", "QuantidadePedidos", "ValorTotalPedidos"])
df_clientes_tot

           Nome  QuantidadePedidos  ValorTotalPedidos
0     Ana Silva                  1              250.0
1  João Pereira                  2              250.0

In [41]:
df_clientes_tot = pd.read_sql_query(query_clientes_tot, conn)
df_clientes_tot

           Nome  QuantidadePedidos  ValorTotalPedidos
0     Ana Silva                  1              250.0
1  João Pereira                  2              250.0

In [42]:
query_pedidos = """
    select
        p.PedidoID,
        p.DataPedido,
        p.ValorTotal
    from Pedidos p
    left join Pagamentos pg
        on p.PedidoID = pg.PedidoID
    where pg.PagamentoID is null
    """
resposta = cursor.execute(query_pedidos).fetchall()
df_pedidos = pd.DataFrame(resposta, columns=["PedidoID", "DataPedido", "ValorTotal"])
df_pedidos

   PedidoID  DataPedido  ValorTotal
0       102  2025-01-12       100.0
1       104  2025-01-17       200.0

In [43]:
df_pedidos = pd.read_sql_query(query_pedidos, conn)
df_pedidos

   PedidoID  DataPedido  ValorTotal
0       102  2025-01-12       100.0
1       104  2025-01-17       200.0